const ADDTODOS = 'ADDTODOS'
const HOMESCREEN = 'HOMESCREEN'
const SIGNINSCREEN = 'SIGNINSCREEN'
const SIGNUPSCREEN = 'SIGNUPSCREEN'
const SPLASHSCREEN = 'SPLASHSCREEN'
const SHOWDATASCREEN = 'SHOWDATASCREEN'
const EDITSCREEN = "EDITSCREEN"
const LOGO = "LOGO"
const WELCOMESCREEN = "WELCOMESCREEN"

export {
    ADDTODOS,
    HOMESCREEN,
    SIGNINSCREEN,
    SIGNUPSCREEN,
    SPLASHSCREEN,
    SHOWDATASCREEN,
    EDITSCREEN,
    LOGO,
    WELCOMESCREEN
}